name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db  # Специальная тестовая БД
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/dev.txt psycopg2-binary
        
    - name: Create test database
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
      run: |
        python -c "
        import psycopg2
        conn = psycopg2.connect('postgres://postgres:postgres@localhost:5432/postgres')
        conn.autocommit = True
        cursor = conn.cursor()
        cursor.execute('CREATE DATABASE test_db;')
        "
        
    - name: Run migrations
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db
      run: |
        python manage.py migrate
        
    - name: Run tests
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db
        DJANGO_SETTINGS_MODULE: config.settings.test
      run: |
        python manage.py test
        
    - name: Check migrations
      run: |
        python manage.py makemigrations --check --dry-run
